### ISSUE TITLE
TLS verification fails on let'sencrypt signed certificates

### ISSUE THREAD

**Issue by ookangzheng** [getdnsapi/stubby#122]
My upstream server details were tested successfully. 
I'm using knot-resolver 2.4 on Ubuntu 18.04 
vps
I'm using brew install stubby on my mac, I got this error
<img width="985" alt="screen shot 2018-07-17 at 22 23 25" src="https://user-images.githubusercontent.com/6301735/42824159-c7344db0-89ce-11e8-94dd-e26ef877e82e.png">

```
// My stubby conf
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_cipher_list: "TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:TLS13-CHACHA20-POLY1305-SHA256:EECDH+AESGCM:EECDH+CHACHA20"
tls_query_padding_blocksize: 256 
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1
  - 0::1
upstream_recursive_servers:
  - address_data: 108.61.201.119
    tls_port: 853
    tls_auth_name: "dns.jp.blandns.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: w3s6fDvmgxonn4S9Q3w02BG5hYsFBm+vq21Ppe9KtSg=
```

My server working good while I tried to do a test with getdnsapi/query
![1-screencapture-getdnsapi-net-query-2018-07-17-22_49_35](https://user-images.githubusercontent.com/6301735/42825049-b2f78dba-89d0-11e8-970b-9c81d29c076d.png)

This is my knot-resolver conf
<img width="1045" alt="screen shot 2018-07-17 at 22 46 40" src="https://user-images.githubusercontent.com/6301735/42824876-4b4491fe-89d0-11e8-9eb5-c9de7ab8df99.png">
