### ISSUE TITLE
Problem cross-compiling for MIPS router support

### ISSUE THREAD

**Issue by john9527** [getdnsapi/stubby#124]
I currently maintain a fork of Asuswrt-Merlin firmware for ASUS routers.   
https://github.com/john9527/asuswrt-merlin

I am trying to integrate getdns/stubby support.   I have successfully built for arm7l based routers, which use a customized kernel 2.6.36.4....it's working very well.

However, trying to build for MIPS routers using a kernel based on 2.6.22.19, I can successfully build/compile, but there are problems running the executable.  Here's some basic info on what I am seeing.  The same yml config runs fine on the ARM routers (I dynamically generate it in the router firmware).  The return code is rather interesting.  Any ideas?
```
admin@RT-N66R-2628:/tmp/home/root# stubby -g -l -C /etc/stubby.yml
Could not configure context with config dict: A required parameter had an invalid value.
Could not parse config file "/etc/stubby.yml": A required parameter had an invalid value.

admin@RT-N66R-2628:/tmp/home/root# echo $?
55

admin@RT-N66R-2628:/tmp/home/root# cat /etc/stubby.yml
tls_ca_file: "/rom/ca-bundle.crt"
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 256
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 10000
tls_backoff_time: 900
appdata_dir: "/var/tmp/stubby"
listen_addresses:
  - 127.0.0.1@5453
upstream_recursive_servers:
# Quad 9
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"

```
