### ISSUE TITLE
stubby.yml question

### ISSUE THREAD

**Issue by waffi121** [getdnsapi/stubby#126]
Hii 

I would like to add two services but I do not understand exactly where I have to copy them.

IP Address: 146.185.167.43:853 or [2a03: b0c0: 0: 1010 :: e9a: 3001]: 853
Alternative Port: 443
TLS hostname: dot.securedns.eu
TLS SPKI Pin:
h3mufC43MEqRD6uE4lz6gAgULZ5 / riqH / E + U + jE3H8g =

I tried adding it to this list:

https://github.com/getdnsapi/stubby/blob/develop/stubby.yml.example

Unfortunately, I can not connect:
STUBBY: Starting DAEMON ....
Could not schedule query: None of the configured upstreams could be used to send queries on the specified transports

Can someone create a list with the entry?

Many Thanks!
regards

**Comment by saradickinson** [comment]
Hi, the example file already contains the details for this server, they are just commented out (lines starting with #). For example the IPv4 address is in the file and when uncommented it looks like this:
```
# dot.securedns.eu
  - address_data: 146.185.167.43
    tls_auth_name: "dot.securedns.eu"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: h3mufC43MEqRD6uE4lz6gAgULZ5/riqH/E+U+jE3H8g=
```
The IPv6 address is later in the file but very similar. Note that this server doesn't offer service on port 443 (only 853)

So just uncomment these two entries and comment or remove the entries in 'DEFAULT UPSTREAMS' and you will be using only this server.
