### ISSUE TITLE
Stubby ignore the conf file

### ISSUE THREAD

**Issue by sarovin** [getdnsapi/stubby#128]
Hi,
i have this configuration:

```
# /etc/stubby/stubby.conf

listen_addresses:
  - 127.0.0.1@8853
  - 0::1@8853

upstream_recursive_servers:
# IPv4 addresses 
# The 1.1.1.1 Cloudflare Servers
 - address_data: 1.1.1.1
 tls_auth_name: "cloudflare-dns.com"
 tls_pubkey_pinset:
 - digest: "sha256"
 value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
 - address_data: 1.0.0.1
 tls_auth_name: "cloudflare-dns.com"
 tls_pubkey_pinset:
 - digest: "sha256" 
 value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
 
# IPv6 addresses 
# The 1.1.1.1 Cloudflare Servers 
 - address_data: 2606:4700:4700::1111
 tls_auth_name: "cloudflare-dns.com"
 tls_pubkey_pinset: 
 - digest: "sha256" 
 value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
 - address_data: 2606:4700:4700::1001
 tls_auth_name: "cloudflare-dns.com"
 tls_pubkey_pinset: 
 - digest: "sha256"
 value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
```

but the service is listening on port 53, as default.

```
$ sudo lsof -Pnl +M -i4 | grep :53  
stubby     430    64707    3u  IPv4  18384      0t0  UDP 127.0.0.1:53 
stubby     430    64707    4u  IPv4  18385      0t0  TCP 127.0.0.1:53 (LISTEN)
```

other info:
- OS: 4.18.5-arch1-1-ARCH
- stubby: 0.2.3

**Comment by sarovin** [comment]
UPDATE:
i have this log:

```
Parser error: while parsing a block collection at line 8, column 2
did not find expected '-' indicator at line 9, column 2
Could not parse config file listen_addresses:
  - 127.0.0.1@8853
  - 0::1@8853
```

**Comment by sarovin** [comment]
Sorry, the problem is the config file:

```
listen_addresses:
  - 127.0.0.1@8053
  - 0::1@8053

## Cloudflare 1.1.1.1 and 1.0.0.1
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"

## Cloudflare servers IPV6
  - address_data: 2606:4700:4700::1111
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 2606:4700:4700::1001
    tls_auth_name: "cloudflare-dns.com"

```
