### ISSUE TITLE
Stubby + DNSSEC question

### ISSUE THREAD

**Issue by Xentrk** [getdnsapi/stubby#136]
I have written a [Stubby installer script](https://github.com/Xentrk/Stubby-Installer-Asuswrt-Merlin) for Asuswrt-Merlin firmware.  I have a few people helping me test.

With the following stubby.yml, DNSSEC test sites [ https://rootcanary.org/test.html]( https://rootcanary.org/test.html) and [http://dnssec.vs.uni-due.de/ ](http://dnssec.vs.uni-due.de/ ) show that DNSSEC is not enabled.

```
# stubby.yml configuration file created by Xentrk
# version 1.0.0
tls_ca_file: "/opt/etc/ssl/certs/ca-certificates.crt"
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
dnssec_return_status: GETDNS_EXTENSION_TRUE
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 0
idle_timeout: 2000
tls_connection_retries: 5
tls_backoff_time: 900
appdata_dir: "/opt/var/cache/stubby"
listen_addresses:
  - 127.0.0.1@5453
  - 0::1@5453

upstream_recursive_servers:
# Quad 9 Secure Primary
#  - address_data: 9.9.9.9
#    tls_auth_name: "dns.quad9.net"
# Quad 9 Secure Primary
#  - address_data: 2620:fe::fe
#    tls_auth_name: "dns.quad9.net"
# Cloudflare Primary IPv4
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
# Cloudflare Primary IPv6
  - address_data: 2606:4700:4700::1111
    tls_auth_name: "cloudflare-dns.com"
```
I do not have any trust anchors in /opt/var/cache/stubby.

With the following stubby.yml, DNSSEC sites [ https://rootcanary.org/test.html]( https://rootcanary.org/test.html) and [http://dnssec.vs.uni-due.de/ ](http://dnssec.vs.uni-due.de/ ) show that DNSSEC is enabled.

```# stubby.yml configuration file created by Xentrk
# version 1.0.1
tls_ca_file: "/opt/etc/ssl/certs/ca-certificates.crt"
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
dnssec_return_status: GETDNS_EXTENSION_TRUE
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 0
idle_timeout: 2000
tls_connection_retries: 5
tls_backoff_time: 900
appdata_dir: "/opt/var/cache/stubby"
listen_addresses:
  - 127.0.0.1@5453
  - 0::1@5453

upstream_recursive_servers:
# Quad 9 Secure Primary
#  - address_data: 9.9.9.9
#    tls_auth_name: "dns.quad9.net"
# Quad 9 Secure Primary
#  - address_data: 2620:fe::fe
#    tls_auth_name: "dns.quad9.net"
# The 1.1.1.1 Cloudflare Servers
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: yioEpqeR4WtDwE9YxNVnCEkTxIjx6EEIwFSQW+lJsbc=
```

I see trust anchors in /opt/var/cache/stubby.  However, the [https://1.1.1.1/help](https://1.1.1.1/help) site does not work.

Others have reported that the  [https://1.1.1.1/help](https://1.1.1.1/help) site does not support DNSSEC.

Is DNSSEC working with the first stubby.yml config file I posted?  

From https://dnsprivacy.org/wiki/display/DP/Configuring+Stubby#ConfiguringStubby-DNSSEC, **dnssec_return_status: GETDNS_EXTENSION_TRUE** will tell Stubby to use DNSSEC and getdns will create the trust anchors.  But no trust anchors are found in **/opt/var/cache/stubby**.

Thank you!
