### ISSUE TITLE
SNI is not being sent

### ISSUE THREAD

**Issue by conblem** [getdnsapi/stubby#241]
I have Stubby configured like this on Windows 10

```yaml
upstream_recursive_servers:
- address_data: 45.90.28.220
  tls_auth_name: "xxxx.dns.nextdns.io"
- address_data: 45.90.30.220
  tls_auth_name: "xxxx.dns.nextdns.io"
```

When i inspect the TLS Client hello there is not SNI extension

![TLS Payload](https://user-images.githubusercontent.com/19853857/79153603-689bd700-7dce-11ea-9de3-a1d1e066c0d5.png)
![Request Overview](https://user-images.githubusercontent.com/19853857/79153648-7d786a80-7dce-11ea-8e79-95a291431a33.png)

Im using nextdns.io which needs the SNI Extension to identify devices.
