### ISSUE TITLE
Can't access Office 365 services (Outlook, Teams, etc)

### ISSUE THREAD

**Issue by moranbw** [getdnsapi/stubby#276]
Hi, really enjoying working with Stubby, a great little solution.  I'm just running into some issues with what seems to be Office 365 authentication to things like Outlook (outlook.microsoft.com) and Teams (teams.microsoft.com).   These seem to redirect to their oauth 2 at https://login.microsoftonline.com, which is failing. Is this a known issue? I've tried logging out, clearing cache, etc, but don't seem to be having any luck. Please let me know if there is any additional information I can provide.  These seem to be the domains requested:

- ajax.googleapis.com
- outlook.office.com
- login.microsoftonline.com

I seem to be able to run things like drill/dig, so not sure if this is TLS related?

I'm running a pretty basic config in a docker container on Debian 10 (used Matthew Vance's config as inspiration: https://github.com/MatthewVance/stubby-docker/blob/master/stubby/Dockerfile):

```
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 10000
tls_ca_path: "/etc/ssl/certs/"
listen_addresses:
  -  0.0.0.0@8053
  -  0:0:0:0:0:0:0:0@8053
dnssec: GETDNS_EXTENSION_TRUE
dnssec_trust_anchors: "/etc/unbound/root.key"
upstream_recursive_servers:
####### IPv4 addresses ######
## Cloudflare 1.1.1.1 and 1.0.0.1
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
```
