### ISSUE TITLE
Chrome saying DNS Lookup failed, NXDOMAIN etc. for a second

### ISSUE THREAD

**Issue by shelterx** [getdnsapi/stubby#303]
I have dnsmasq, adblock and stubby together in OpenWRT. Works great.
However when I browse with Google Chrome, it seems like Chrome do an initial lookup of some sort 'cause I get that the hostname can't be resolved but it seems to do another lookup after and loads the page.

How do I fix this? It does not happen in Firefox, I haven't seen any other issues either other than with Chrome.

**Comment by shelterx** [comment]
Hmm it could be adblock doing something funky, I disabled it and now it seems to work fine.
So for some reason adblock doesn't cope with stubby and dnsmasq. At least not for me.

**Comment by shelterx** [comment]
If i bypass stubby by using cloudflare non-encrypted DNS in OpenWrt it works fine.... 
My config:
```
resolution_type: GETDNS_RESOLUTION_STUB
round_robin_upstreams: 1
appdata_dir: "/var/lib/stubby"
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private: 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1@5453
  - 0::1@5453
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
upstream_recursive_servers:
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"

```
