### ISSUE TITLE
Cloudflare DoT w/multiple requests = DNSSEC fail until connection closed

### ISSUE THREAD

**Issue by uzlonewolf** [getdnsapi/stubby#331]
So, I don't know if this is a Cloudflare, Stubby, or GetDNS bug, but when Stubby is configured to use only Cloudflare and multiple requests for the same name are sent, both of those requests plus every request sent after that point will fail.  Things only start working again once the connection has been idle long enough to be closed.

Using this configuration:
```yaml
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 0
idle_timeout: 10000
tls_min_version: GETDNS_TLS1_2
listen_addresses: 
  - 127.0.0.1@9953
  - 0::1@9953
dnssec: GETDNS_EXTENSION_TRUE
appdata_dir: "/var/cache/stubby"
dnssec_trust_anchors: "/var/lib/unbound/root.key"
upstream_recursive_servers:
## Cloudflare 1.1.1.1 and 1.0.0.1
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
```
I can reliably get it to fall over with:
```bash
dig @0 -p 9953 google.com; dig @0 -p 9953 google.com & dig @0 -p 9953 google.com
```
Changing `round_robin_upstreams: 0` to `round_robin_upstreams: 1` makes it take slightly longer, but it still happens if you run the above 2-3 times.

Recompiling GetDNS with full debugging enabled shows that once the bug is triggered, every subsequent request over that TLS/TCP connection will result in a DNSSEC failure.  Once that happens, Stubby/GetDNS just sits there and times out instead of retrying with the next server.

I have not tried DoH, but this does not happen with Google's DoT servers.
