### ISSUE TITLE
trying to create my own stubby.yml file - Could not parse config file "/etc/stubby/stubby.yml": Generic error

### ISSUE THREAD

**Issue by blub4747** [getdnsapi/stubby#366]
Hello community,
I am trying to built my own stubby.yml file and it keeps complaining.
Also when is stubby really that picky, that it will complain, if there is another file called stubby.blah.
For when I playing and forward with the config file.
Thx,blub4747`
`

**Comment by saradickinson** [comment]
The yaml is sensitive to indentation and some fields require a specific syntax as we use a slightly none standard parser. The presence of another file called `stubby.blah` will not affect processing. One thing to check is the stubby logs to make sure it is reading the file you think it is (the path is reported there) - depending on the platform it will search several directories in a specific order for a file called `stubby.yml`. 

If you are not comfortable sharing you own file here, you can email me directly and I will take look:  sara@sinodun.com

**Comment by blub4747** [comment]
Hi Sarah, 
Sorry about my missing .yml file.
I just noticed that GitHub will not let me upload .yml files.
I though that forgot to add it.

[stubby.zip](https://github.com/user-attachments/files/20203948/stubby.zip)

**Comment by saradickinson** [comment]
Hi there - thanks for the file. The problem was with the upstream section which was missing the `upstream_recursive_servers` heading and needed some changes to the implementation. The text below should work. 

Also, I misunderstood your question - the file does need to have a `.yml` extension. This is so stubby knows how to parse it (there was previously support for `json` files and the file extension is the only way the code knows which syntax to use. ) So you need to rename your file to something like `stubby_blah.yml`. (The parser error messages are not very helpful - sorry!)

```
dns_transport_list: 
  - GETDNS_TRANSPORT_TLS

tls_authentication: GETDNS_AUTHENTICATION_REQUIRED

tls_query_padding_blocksize: 256

edns_client_subnet_private : 1
round_robin_upstreams: 1

idle_timeout: 10000

listen_addresses:
  - 127.0.0.1
  -  0::1

upstream_recursive_servers:
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"
    tls_pubkey_pinset:
     - digest: "sha256"
       value: MujBQ+U0p2eZLTnQ2KGEqs+fPLYV/1DnpZDjBDPwUqQ=

dnssec_return_status: GETDNS_EXTENSION_TRUE
```
