### ISSUE TITLE
Question: How will Quad9 affect stubby?

### ISSUE THREAD

**Issue by mi-hol** [getdnsapi/stubby#45]
I wonder how [Quad9](https://quad9.net/#/about ) will affect stubby?
i.e will there be a collaboration with Quad9 or sharing of DNS servers?
...

**Comment by woopstar** [comment]
According to Quad9 they support DNS over TLS. But I am unable to find any information about the TLS hostname, SPKI etc.

They do support DNSSEC.

**Comment by woopstar** [comment]
Oh. Found info:

```
upstream_recursive_servers:
# Quad9
   - address_data: 9.9.9.9
     tls_auth_name: "dns.quad9.net"
   - address_data: 2620:fe::fe
     tls_auth_name: "dns.quad9.net"
```

Ref: http://www.bortzmeyer.org/quad9.html
