### ISSUE TITLE
Enabling DNSSEC prevents access to bank.barclays.co.uk

### ISSUE THREAD

**Issue by UniverseXXX** [getdnsapi/stubby#99]
Hi,
I’m running stubby on Lede/OpenWRT. Once the DNSSEC is enabled in config, I cannot access bank.barclays.co.uk (in web browser or using native Barclays iOS app) anymore.
Please advise if there is something needs to be done or that’s a bug?
Thanks.

```
resolution_type:GETDNS_RESOLUTION_STUB

dns_transport_list:
  - GETDNS_TRANSPORT_TLS

tls_authentication: GETDNS_AUTHENTICATION_REQUIRED

tls_query_padding_blocksize: 256

edns_client_subnet_private : 0

idle_timeout: 10000

dnssec_return_status: GETDNS_EXTENSION_TRUE
#dnssec_trust_anchors: "/etc/unbound/getdns-root.key"

listen_addresses:
  - 127.0.0.1@5453
  -  0::1@5453

round_robin_upstreams: 0

upstream_recursive_servers:

#------CloudFlare----------------------------------------------------
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"

  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"

#------QUAD 9-------------------------------------------------------
# # Quad 9 IPv6
  - address_data: 2620:fe::fe
    tls_auth_name: "dns.quad9.net"

# # Quad 9 IPv4
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"

#------SurfNet/Sinodun-----------------------------------------------
# The Surfnet/Sinodun servers
  - address_data: 145.100.185.15
    tls_auth_name: "dnsovertls.sinodun.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: 62lKu9HsDVbyiPenApnc4sfmSYTHOVfFgL3pyB+cBL4=

  - address_data: 145.100.185.16
    tls_auth_name: "dnsovertls1.sinodun.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: cE2ecALeE5B+urJhDrJlVFmf38cJLAvqekONvjvpqUA=

#------GetDNSAPI-----------------------------------------------------
# # The getdnsapi.net server
  - address_data: 185.49.141.37
    tls_auth_name: "getdnsapi.net"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q=

#------SecureDNS.eu--------------------------------------------------
# # Securedns.eu
  - address_data: 146.185.167.43
    tls_auth_name: "securedns.eu"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: 2EfbwDyk2zSnAbBJSpCSWZKKGUD+a6p/yg2bxdC+x2A=

#------NS DNS Privacy------------------------------------------------
  - address_data: 94.130.110.185
    tls_auth_name: "ns1.dnsprivacy.at"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: vqVQ9TcoR9RDY3TpO0MTXw1YQLjF44zdN3/4PkLwtEY=
  - address_data: 94.130.110.178
    tls_auth_name: "ns2.dnsprivacy.at"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: s5Em89o0kigwfBF1gcXWd8zlATSWVXsJ6ecZfmBDTKg=
```
